/**
 * Environment File Generator
 *
 * Generates Angular environment files from environment variables.
 * Loads .env file for local development, uses system env vars in CI/CD.
 *
 * Usage:
 *   npx ts-node scripts/set-env.ts          # Generates both environment files
 *   npx ts-node scripts/set-env.ts --prod   # Generates only production environment
 *
 * Required environment variables:
 *   FIREBASE_API_KEY
 *   FIREBASE_PROJECT_ID
 *   FIREBASE_APP_ID
 *   FIREBASE_SENDER_ID
 */

import { config } from 'dotenv';
import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';

const envPath = join(__dirname, '..', '.env');
if (existsSync(envPath)) {
  config({ path: envPath });
  console.log('Loaded .env file');
}

interface FirebaseConfig {
  apiKey: string;
  authDomain: string;
  projectId: string;
  storageBucket: string;
  messagingSenderId: string;
  appId: string;
  measurementId?: string;
}

interface Environment {
  production: boolean;
  firebase: FirebaseConfig;
}

function getEnvVar(name: string, fallback = ''): string {
  return process.env[name] || fallback;
}

function generateEnvironmentContent(env: Environment): string {
  return `// This file is auto-generated. Do not edit manually.
// Generated by scripts/set-env.ts

export const environment = {
  production: ${env.production},
  firebase: {
    apiKey: '${env.firebase.apiKey}',
    authDomain: '${env.firebase.authDomain}',
    projectId: '${env.firebase.projectId}',
    storageBucket: '${env.firebase.storageBucket}',
    messagingSenderId: '${env.firebase.messagingSenderId}',
    appId: '${env.firebase.appId}',
    measurementId: '${env.firebase.measurementId}',
  },
};
`;
}

function createFirebaseConfig(): FirebaseConfig {
  const projectId = getEnvVar('FIREBASE_PROJECT_ID', 'YOUR_PROJECT_ID');

  return {
    apiKey: getEnvVar('FIREBASE_API_KEY', 'YOUR_API_KEY'),
    authDomain: `${projectId}.firebaseapp.com`,
    projectId: projectId,
    storageBucket: `${projectId}.firebasestorage.com`,
    messagingSenderId: getEnvVar('FIREBASE_SENDER_ID', 'YOUR_SENDER_ID'),
    appId: getEnvVar('FIREBASE_APP_ID', 'YOUR_APP_ID'),
    measurementId: getEnvVar('FIREBASE_MEASUREMENT_ID', 'YOUR_MEASUREMENT_ID'),
  };
}

function main(): void {
  const args = process.argv.slice(2);
  const prodOnly = args.includes('--prod');

  const environmentsDir = join(__dirname, '..', 'src', 'environments');

  if (!existsSync(environmentsDir)) {
    mkdirSync(environmentsDir, { recursive: true });
  }

  const firebaseConfig = createFirebaseConfig();

  if (!prodOnly) {
    const devEnv: Environment = {
      production: false,
      firebase: firebaseConfig,
    };

    const devPath = join(environmentsDir, 'environment.ts');
    writeFileSync(devPath, generateEnvironmentContent(devEnv));
    console.log(`Generated: ${devPath}`);
  }

  const prodEnv: Environment = {
    production: true,
    firebase: firebaseConfig,
  };

  const prodPath = join(environmentsDir, 'environment.prod.ts');
  writeFileSync(prodPath, generateEnvironmentContent(prodEnv));
  console.log(`Generated: ${prodPath}`);

  const hasPlaceholders = Object.values(firebaseConfig).some(
    (value) => value.includes('YOUR_') || value === '' || value === 'undefined'
  );

  if (hasPlaceholders) {
    console.warn(
      '\nWarning: Some environment variables are not set. Using placeholder values.'
    );
    console.warn('Required environment variables:');
    console.warn('  - FIREBASE_API_KEY');
    console.warn('  - FIREBASE_PROJECT_ID');
    console.warn('  - FIREBASE_APP_ID');
    console.warn('  - FIREBASE_SENDER_ID');
    console.warn('  - FIREBASE_MEASUREMENT_ID');
  }
}

main();
