/**
 * Environment File Generator
 *
 * Generates Angular environment files from environment variables.
 * Loads .env file for local development, uses system env vars in CI/CD.
 *
 * Usage:
 *   npx ts-node scripts/set-env.ts          # Generates both environment files
 *   npx ts-node scripts/set-env.ts --prod   # Generates only production environment
 *
 * Required environment variables:
 *   PRIMENG_UI_KEY
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { config } from 'dotenv';

const envPath = join(__dirname, '..', '.env');
if (existsSync(envPath)) {
  config({ path: envPath });
  console.log('Loaded .env file');
}

interface Environment {
  production: boolean;
  primengLicense: string;
}

function getEnvVar(name: string, fallback = ''): string {
  return process.env[name] || fallback;
}

function generateEnvironmentContent(env: Environment): string {
  return `// This file is auto-generated. Do not edit manually.
// Generated by scripts/set-env.ts

export const environment = {
  production: ${env.production},
  primengLicense: '${env.primengLicense}',
};
`;
}

function main(): void {
  const args = process.argv.slice(2);
  const prodOnly = args.includes('--prod');

  const environmentsDir = join(__dirname, '..', 'src', 'environments');

  if (!existsSync(environmentsDir)) {
    mkdirSync(environmentsDir, { recursive: true });
  }

  const primengLicense = getEnvVar('PRIMENG_UI_KEY');

  if (!prodOnly) {
    const devEnv: Environment = {
      production: false,
      primengLicense,
    };

    const devPath = join(environmentsDir, 'environment.ts');
    writeFileSync(devPath, generateEnvironmentContent(devEnv));
    console.log(`Generated: ${devPath}`);
  }

  const prodEnv: Environment = {
    production: true,
    primengLicense,
  };

  const prodPath = join(environmentsDir, 'environment.prod.ts');
  writeFileSync(prodPath, generateEnvironmentContent(prodEnv));
  console.log(`Generated: ${prodPath}`);

  if (!primengLicense) {
    console.warn(
      '\nWarning: PRIMENG_UI_KEY is not set. PrimeNG will render its "Invalid PrimeUI License" banner.'
    );
  }
}

main();
